@startuml

!include <C4/C4_Component>

Component(App, "Application", "consumer")
Component(MetrigoClient, "Metrigo\nClient\nLib", "Java Library")
Component(MetricAdapter, "Metric\nSend\nAdapter", "Java Library")
Component(MetricDB, "Metric\nDatabase", "DB (Mongo/etc.)")
Component(Metrigo_PerfViz, "Performance\nVisualizer", "Application")

Rel(App, MetrigoClient, "mark metrics")
Rel(MetrigoClient, MetricAdapter, "send metrics")
Rel(MetricAdapter, MetricDB, "store metrics")
Rel(Metrigo_PerfViz, MetricDB, "get data")

@enduml